# Generated by Django 3.0 on 2020-04-27 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sixseveneightresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField()),
                ('nepali', models.IntegerField()),
                ('math', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('Social', models.IntegerField()),
                ('ehp', models.IntegerField()),
                ('computer', models.IntegerField()),
                ('grammar', models.IntegerField()),
                ('optionalmath', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanagement.Student_info')),
            ],
        ),
        migrations.CreateModel(
            name='onetwothreeresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField()),
                ('nepali', models.IntegerField()),
                ('math', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('Social', models.IntegerField()),
                ('gk', models.IntegerField()),
                ('drawing', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanagement.Student_info')),
            ],
        ),
        migrations.CreateModel(
            name='ninetenresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField()),
                ('nepali', models.IntegerField()),
                ('math', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('Social', models.IntegerField()),
                ('ehp', models.IntegerField()),
                ('optionali', models.IntegerField()),
                ('oprionalii', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanagement.Student_info')),
            ],
        ),
        migrations.CreateModel(
            name='fourfiveresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField()),
                ('nepali', models.IntegerField()),
                ('math', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('Social', models.IntegerField()),
                ('computer', models.IntegerField()),
                ('gk', models.IntegerField()),
                ('grammar', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanagement.Student_info')),
            ],
        ),
    ]
