# Generated by Django 3.0 on 2020-04-27 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0003_auto_20200427_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('english', models.IntegerField()),
                ('nepali', models.IntegerField()),
                ('math', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('Social', models.IntegerField()),
                ('ehp', models.IntegerField(blank=True)),
                ('optionali', models.IntegerField(blank=True)),
                ('oprionalii', models.IntegerField(blank=True)),
                ('grammar', models.IntegerField(blank=True)),
                ('optionalmath', models.IntegerField(blank=True)),
                ('computer', models.IntegerField(blank=True)),
                ('gk', models.IntegerField(blank=True)),
                ('drawing', models.IntegerField(blank=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanagement.Student_info')),
            ],
        ),
        migrations.RemoveField(
            model_name='nine_ten_result',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='one_two_three_result',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='six_seven_eight_result',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Four_Five_Result',
        ),
        migrations.DeleteModel(
            name='Nine_Ten_Result',
        ),
        migrations.DeleteModel(
            name='One_Two_Three_Result',
        ),
        migrations.DeleteModel(
            name='Six_Seven_Eight_Result',
        ),
    ]
