# Generated by Django 3.0 on 2020-04-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0010_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='oprionalii',
            new_name='optionalii',
        ),
    ]
