# Generated by Django 3.0 on 2020-04-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0013_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('admission', models.IntegerField()),
                ('baisakh', models.IntegerField()),
                ('jestha', models.IntegerField()),
                ('ashad', models.IntegerField()),
                ('shrawan', models.IntegerField()),
                ('bhadra', models.IntegerField()),
                ('aswin', models.IntegerField()),
                ('kartik', models.IntegerField()),
                ('mangsir', models.IntegerField()),
                ('poush', models.IntegerField()),
                ('magh', models.IntegerField()),
                ('falgun', models.IntegerField()),
                ('chaitra', models.IntegerField()),
            ],
        ),
    ]
