# Generated by Django 3.0 on 2020-04-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0014_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='ashad',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='aswin',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='baisakh',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bhadra',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='chaitra',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='falgun',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='jestha',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='kartik',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='magh',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='mangsir',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='poush',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='shrawan',
            field=models.IntegerField(blank=True),
        ),
    ]
