# Generated by Django 3.0 on 2020-04-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0015_auto_20200429_0201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
