# Generated by Django 3.0 on 2020-04-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0017_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
