# Generated by Django 3.0 on 2020-05-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0020_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='student_id',
            new_name='sid',
        ),
    ]
